export const legoHeads = [
  {
    locX: 1,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 4,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 6,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 9,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 1,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 1,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 1,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 1,
    male: true,
    beard: false,
    stubble: true,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 3,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 4,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 6,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 2,
    locY: 15,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 2,
    locY: 16,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 2,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 4,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 7,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 8,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 9,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 3,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 3,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 3,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 1,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 4,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 6,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 8,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 10,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 4,
    locY: 14,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 4,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 5,
    locY: 5,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 8,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 12,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 5,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 5,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 5,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 6,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 7,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 8,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 6,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 13,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 6,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 6,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 7,
    locY: 1,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 2,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 7,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 6,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 7,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 10,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 7,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 7,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 7,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 8,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 8,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 8,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 8,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 8,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 8,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 8,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 9,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 8,
    locY: 10,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 8,
    locY: 12,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 8,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 8,
    locY: 15,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 8,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 1,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 4,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 9,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 9,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 9,
    locY: 14,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 9,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 4,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 5,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 10,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 10,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 10,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 10,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 10,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 11,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 8,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 10,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 11,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 14,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 11,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 12,
    locY: 1,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 12,
    locY: 4,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 12,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 7,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 12,
    locY: 8,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 12,
    locY: 11,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 12,
    locY: 13,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 12,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 12,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 12,
    locY: 16,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 1,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 2,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 3,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 13,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 13,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 6,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 13,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 8,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 13,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 13,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 11,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 13,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 13,
    locY: 14,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 13,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 13,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 14,
    locY: 6,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 8,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 14,
    locY: 9,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 10,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 12,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 14,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 14,
    locY: 15,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 14,
    locY: 16,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 15,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 4,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 7,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 8,
    male: true,
    beard: true,
    stubble: true,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 9,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 15,
    locY: 10,
    male: true,
    beard: true,
    stubble: true,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 11,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 15,
    locY: 15,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 15,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 16,
    locY: 3,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 16,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 16,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: true,
  },
  {
    locX: 16,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 16,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 8,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 16,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 16,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 16,
    locY: 16,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 6,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 7,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 8,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 17,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 17,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 14,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 17,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 1,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 2,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 3,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 6,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 7,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 9,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 10,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 11,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 12,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 14,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 18,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 18,
    locY: 16,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 1,
    male: true,
    beard: true,
    stubble: true,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 19,
    locY: 3,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 19,
    locY: 4,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 5,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 19,
    locY: 6,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 19,
    locY: 7,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 8,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 19,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 19,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 19,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 12,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 13,
    male: true,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 14,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 19,
    locY: 15,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 19,
    locY: 16,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 1,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 2,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 3,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 4,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 5,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 6,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 7,
    male: true,
    beard: true,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 8,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 9,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 10,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 11,
    male: false,
    beard: false,
    stubble: false,
    eyewear: true,
    mouthOpen: true,
    extra: false,
  },
  {
    locX: 20,
    locY: 12,
    male: true,
    beard: false,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 13,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: true,
    extra: true,
  },
  {
    locX: 20,
    locY: 14,
    male: true,
    beard: true,
    stubble: true,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 15,
    male: true,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
  {
    locX: 20,
    locY: 16,
    male: false,
    beard: false,
    stubble: false,
    eyewear: false,
    mouthOpen: false,
    extra: false,
  },
];
